In [16]:
import kagglehub

path = kagglehub.dataset_download("martj42/womens-international-football-results")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Path to dataset files: /Users/veronica/.cache/kagglehub/datasets/martj42/womens-international-football-results/versions/36

In [17]:
import os
import pandas as pd

# List all CSV files in the directory
csv_files = [file for file in os.listdir(path) if file.endswith('.csv')]

# Read each CSV file into a DataFrame
dataframes = {file: pd.read_csv(os.path.join(path, file)) for file in csv_files}

# Print the names of the loaded DataFrames
print("Loaded DataFrames:", list(dataframes.keys()))

Loaded DataFrames: ['goalscorers.csv', 'shootouts.csv', 'results.csv']

In [18]:
goalscorers_df = dataframes.get('goalscorers.csv')
shootouts_df = dataframes.get('shootouts.csv')
results_df = dataframes.get('results.csv')

display(goalscorers_df)
display(shootouts_df)
display(results_df)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1984-04-08,England,Denmark,England,Linda Curl,31,False,False
1,1984-04-08,England,Denmark,Denmark,Inge Hindkjær,49,False,True
2,1984-04-08,England,Denmark,England,Elisabeth Deighan,51,False,False
3,1984-04-08,Italy,Sweden,Italy,Carolina Morace,18,False,False
4,1984-04-08,Italy,Sweden,Sweden,Helen Johansson,23,False,False
...,...,...,...,...,...,...,...,...
2790,2025-07-22,England,Italy,England,Michelle Agyemang,90,False,False
2791,2025-07-22,England,Italy,England,Chloe Kelly,119,False,False
2792,2025-07-23,Germany,Spain,Spain,Aitana Bonmatí,113,False,False
2793,2025-07-27,England,Spain,Spain,Mariona Caldentey,25,False,False
2794,2025-07-27,England,Spain,England,Alessia Russo,57,False,False

           date     home_team  away_team     winner first_shooter
0    1984-05-27       England     Sweden     Sweden           NaN
1    1988-06-12      China PR     Brazil     Brazil        Brazil
2    1995-06-13        Sweden   China PR   China PR      China PR
3    1996-05-18         Japan     Canada      Japan           NaN
4    1998-07-25      China PR     Norway   China PR           NaN
..          ...           ...        ...        ...           ...
129  2025-11-30  Saudi Arabia  Palestine  Palestine           NaN
130  2025-12-02  Saudi Arabia       Iraq       Iraq           NaN
131  2025-02-26      Zimbabwe     Angola     Angola           NaN
132  2025-02-26      Ethiopia     Uganda   Ethiopia           NaN
133  2025-10-28   Ivory Coast    Senegal    Senegal           NaN

[134 rows x 5 columns]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1956-09-23,Germany,Netherlands,2,1,Friendly,Essen,Germany,False
1,1957-07-28,Germany,England,1,1,Friendly,Stuttgart,Germany,False
2,1957-10-13,Germany,Netherlands,2,0,Friendly,Berlin,Germany,False
3,1957-11-03,Netherlands,Austria,8,1,European Championship,Berlin,Germany,True
4,1957-11-03,Germany,England,0,4,European Championship,Berlin,Germany,False
...,...,...,...,...,...,...,...,...,...
11172,2025-12-02,Scotland,China PR,3,2,Friendly,Jerez De La Frontera,Spain,True
11173,2025-12-02,England,Ghana,2,0,Friendly,Southampton,England,False
11174,2025-12-02,Netherlands,South Korea,5,0,Friendly,Waalwijk,Netherlands,False
11175,2025-12-02,Portugal,Brazil,0,5,Friendly,Aveiro,Portugal,False
11176,2025-12-03,Costa Rica,Mexico,0,2,Friendly,Alajuela,Costa Rica,False

In [19]:
# Convert 'date' columns to datetime
results_df['date'] = pd.to_datetime(results_df['date'], errors='coerce')
shootouts_df['date'] = pd.to_datetime(shootouts_df['date'], errors='coerce')
goalscorers_df['date'] = pd.to_datetime(goalscorers_df['date'], errors='coerce')

In [20]:
# Check for null dates
print(results_df['date'].isna().sum())
print(shootouts_df['date'].isna().sum())
print(goalscorers_df['date'].isna().sum())

0
0
0

### Clean team names and strings

In [21]:
# Clean team names and strings
def clean_team_names(df, columns):
    for col in columns:
        df[col] = (
            df[col]
            .astype(str)
            .str.strip()
            .str.replace(r'\s+', ' ', regex=True)
        )
    return df

goalscorers_df = clean_team_names(goalscorers_df, ['home_team', 'away_team', 'team', 'scorer'])
shootouts_df = clean_team_names(shootouts_df, ['home_team', 'away_team', 'winner', 'first_shooter'])
results_df = clean_team_names(results_df, ['home_team', 'away_team', 'tournament', 'city', 'country'])

### Normalize team names/countries acrosss datasets

In [22]:
teams_results = set(results_df['home_team']).union(set(results_df['away_team']))
teams_shootouts = set(shootouts_df['home_team']).union(set(shootouts_df['away_team']))
teams_goalscorers = set(goalscorers_df['team'])

all_teams = teams_results.union(teams_shootouts).union(teams_goalscorers)
print(f"Total unique teams across datasets: {len(all_teams)}")

Total unique teams across datasets: 247

In [23]:
# Save to CSV to manually review
pd.Series(sorted(all_teams)).to_csv('data/unique_team_names.csv', index=False)

In [24]:
team_name_map = {
    "United States Virgin Islands": "U.S. Virgin Islands",
    "Curacao": "Curaçao",
    "Shetland Islands": "Shetland",
}

def map_team_names(df, columns, name_map):
    for col in columns:
        df[col] = df[col].replace(name_map)
    return df

results_df = map_team_names(results_df, ['home_team', 'away_team', 'country'], team_name_map)
shootouts_df = map_team_names(shootouts_df, ['home_team', 'away_team', 'winner', 'first_shooter'], team_name_map)
goalscorers_df = map_team_names(goalscorers_df, ['home_team', 'away_team', 'team'], team_name_map)

### Assign unique match_id keys

In [25]:
# match_id = YYYY-MM-DD_homeTeam_awayTeam

def create_match_id(df):
    return (
        df['date'].dt.strftime('%Y-%m-%d') + '_' +
        df['home_team'].str.replace(' ', '_') + '_' +
        df['away_team'].str.replace(' ', '_')
    )

results_df['match_id'] = create_match_id(results_df)
shootouts_df['match_id'] = create_match_id(shootouts_df)
goalscorers_df['match_id'] = create_match_id(goalscorers_df)

In [26]:
## Checking for duplicates
print("Results duplicates:", results_df['match_id'].duplicated().sum())
print("Shootouts duplicates:", shootouts_df['match_id'].duplicated().sum())
print("Goalscorers duplicates:", goalscorers_df['match_id'].duplicated().sum())

Results duplicates: 0
Shootouts duplicates: 2
Goalscorers duplicates: 1908

In [27]:
display(results_df)
display(shootouts_df)
display(goalscorers_df)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,match_id
0,1956-09-23,Germany,Netherlands,2,1,Friendly,Essen,Germany,False,1956-09-23_Germany_Netherlands
1,1957-07-28,Germany,England,1,1,Friendly,Stuttgart,Germany,False,1957-07-28_Germany_England
2,1957-10-13,Germany,Netherlands,2,0,Friendly,Berlin,Germany,False,1957-10-13_Germany_Netherlands
3,1957-11-03,Netherlands,Austria,8,1,European Championship,Berlin,Germany,True,1957-11-03_Netherlands_Austria
4,1957-11-03,Germany,England,0,4,European Championship,Berlin,Germany,False,1957-11-03_Germany_England
...,...,...,...,...,...,...,...,...,...,...
11172,2025-12-02,Scotland,China PR,3,2,Friendly,Jerez De La Frontera,Spain,True,2025-12-02_Scotland_China_PR
11173,2025-12-02,England,Ghana,2,0,Friendly,Southampton,England,False,2025-12-02_England_Ghana
11174,2025-12-02,Netherlands,South Korea,5,0,Friendly,Waalwijk,Netherlands,False,2025-12-02_Netherlands_South_Korea
11175,2025-12-02,Portugal,Brazil,0,5,Friendly,Aveiro,Portugal,False,2025-12-02_Portugal_Brazil
11176,2025-12-03,Costa Rica,Mexico,0,2,Friendly,Alajuela,Costa Rica,False,2025-12-03_Costa_Rica_Mexico

,date,home_team,away_team,winner,first_shooter,match_id
0,1984-05-27,England,Sweden,Sweden,nan,1984-05-27_England_Sweden
1,1988-06-12,China PR,Brazil,Brazil,Brazil,1988-06-12_China_PR_Brazil
2,1995-06-13,Sweden,China PR,China PR,China PR,1995-06-13_Sweden_China_PR
3,1996-05-18,Japan,Canada,Japan,nan,1996-05-18_Japan_Canada
4,1998-07-25,China PR,Norway,China PR,nan,1998-07-25_China_PR_Norway
...,...,...,...,...,...,...
129,2025-11-30,Saudi Arabia,Palestine,Palestine,nan,2025-11-30_Saudi_Arabia_Palestine
130,2025-12-02,Saudi Arabia,Iraq,Iraq,nan,2025-12-02_Saudi_Arabia_Iraq
131,2025-02-26,Zimbabwe,Angola,Angola,nan,2025-02-26_Zimbabwe_Angola
132,2025-02-26,Ethiopia,Uganda,Ethiopia,nan,2025-02-26_Ethiopia_Uganda
133,2025-10-28,Ivory Coast,Senegal,Senegal,nan,2025-10-28_Ivory_Coast_Senegal

,date,home_team,away_team,team,scorer,minute,own_goal,penalty,match_id
0,1984-04-08,England,Denmark,England,Linda Curl,31,False,False,1984-04-08_England_Denmark
1,1984-04-08,England,Denmark,Denmark,Inge Hindkjær,49,False,True,1984-04-08_England_Denmark
2,1984-04-08,England,Denmark,England,Elisabeth Deighan,51,False,False,1984-04-08_England_Denmark
3,1984-04-08,Italy,Sweden,Italy,Carolina Morace,18,False,False,1984-04-08_Italy_Sweden
4,1984-04-08,Italy,Sweden,Sweden,Helen Johansson,23,False,False,1984-04-08_Italy_Sweden
...,...,...,...,...,...,...,...,...,...
2790,2025-07-22,England,Italy,England,Michelle Agyemang,90,False,False,2025-07-22_England_Italy
2791,2025-07-22,England,Italy,England,Chloe Kelly,119,False,False,2025-07-22_England_Italy
2792,2025-07-23,Germany,Spain,Spain,Aitana Bonmatí,113,False,False,2025-07-23_Germany_Spain
2793,2025-07-27,England,Spain,Spain,Mariona Caldentey,25,False,False,2025-07-27_England_Spain
2794,2025-07-27,England,Spain,England,Alessia Russo,57,False,False,2025-07-27_England_Spain

In [28]:
results_df.merge(
    shootouts_df[['match_id', 'winner']],
    on='match_id',
    how='right'
)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,match_id,winner
0,1984-05-27,England,Sweden,1,0,UEFA Euro,Luton,England,False,1984-05-27_England_Sweden,Sweden
1,1988-06-12,China PR,Brazil,0,0,FIFA Women's Invitation Tournament,Guangzhou,China PR,False,1988-06-12_China_PR_Brazil,Brazil
2,1995-06-13,Sweden,China PR,1,1,FIFA World Cup,Helsingborg,Sweden,False,1995-06-13_Sweden_China_PR,China PR
3,1996-05-18,Japan,Canada,0,0,U.S. Cup,"Washington, D.C.",United States,True,1996-05-18_Japan_Canada,Japan
4,1998-07-25,China PR,Norway,1,1,Goodwill Games,Uniondale,United States,True,1998-07-25_China_PR_Norway,China PR
...,...,...,...,...,...,...,...,...,...,...,...
129,2025-11-30,Saudi Arabia,Palestine,0,0,WAFF Women's Championship,Jeddah,Saudi Arabia,False,2025-11-30_Saudi_Arabia_Palestine,Palestine
130,2025-12-02,Saudi Arabia,Iraq,2,2,WAFF Women's Championship,Jeddah,Saudi Arabia,False,2025-12-02_Saudi_Arabia_Iraq,Iraq
131,2025-02-26,Zimbabwe,Angola,2,1,Africa Cup of Nations qualification,Pretoria,South Africa,True,2025-02-26_Zimbabwe_Angola,Angola
132,2025-02-26,Ethiopia,Uganda,2,0,Africa Cup of Nations qualification,Addis Ababa,Ethiopia,False,2025-02-26_Ethiopia_Uganda,Ethiopia
133,2025-10-28,Ivory Coast,Senegal,0,0,Africa Cup of Nations qualification,Abidjan,Ivory Coast,False,2025-10-28_Ivory_Coast_Senegal,Senegal

In [29]:
# Exporting clean files
results_df.to_csv('data/results_clean.csv', index=False)
shootouts_df.to_csv('data/shootouts_clean.csv', index=False)
goalscorers_df.to_csv('data/goalscorers_clean.csv', index=False)